name: Node.js CI/CD

on:
  push:
    branches:
      - master  # Adjust this branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.5.1  # Adjust the version as needed

      - name: Install project dependencies
        run: npm install

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/bideshonline_back
            git pull origin master  # Or use your preferred deployment method
            npm install --production
            pm2 restart 0  # Restart your Node.js app
