name: CI/CD

on:
  push:
    branches:
      - master 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Deploy
        run: |
          sshpass -p ${{ secrets.SSHPASS }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }} << EOF
            cd /root/bideshonline_back
            git pull origin master 
            npm install
            npm run build
            pm2 restart app
          EOF