name: CI/CD

on:
  push:
    branches:
      - master 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: appleboy/ssh-action@master
        with: 
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USER}}

          script: |
            cd bideshonline_back
            git pull https://github.com/cybertrontech/bideshonline_back.git
            npm install
            pm2 restart 0
            sudo systemctl restart nginx
            echo 'Deployment success s'